
(ns madra.príomh
  (:require [madra.Draíoch.bunus :as b]
            [madra.Draíoch.stát :as s]
            [madra.Draíoch.app :as app]
            [madra.feidhmchlár.teagmhais :as teagmhais]
            [madra.feidhmchlár.síntiúis :as síntiúis]
            [madra.feidhmchlár.éifeachtaí :as éifeachtaí]
            [madra.comhéadan.scáileáin.ceachtanna :as ceachtanna]))

(b/Sainigh main []
  (teagmhais/cláraigh-teagmhais!)
  (síntiúis/cláraigh-síntiúis!)
  (éifeachtaí/cláraigh-éifeachtaí!)

  (s/Seol [::teagmhais/tús])
  (s/Seol [::teagmhais/lódáil-paca])

  (app/Rith
   (app/FeidhmchlárÁbhair
    :teideal "Gaeilge"
    :baile (ceachtanna/scáileán-ceachtanna))))
